[env]
custom_loomane_version_major = 0
custom_loomane_version_minor = 4

board_build.partitions = include/lm/board/${this.board}/lm/partitions.csv
board_build.filesystem = fatfs

build_src_filter = +<lm/> -<lm/arch/> +<../lib/tinyusb/src/> -<../lib/tinyusb/src/portable/>

monitor_speed = 115200
monitor_raw = yes

build_flags =
    -Iinclude/lm/board/${this.board}
    -Iinclude/lm/usbd/internal # tusb_config.h

extra_scripts =
    pre:scripts/pio_silence.py # Silence some pesky warnings from other projects.
    pre:scripts/pio_gen_defs.py # Generate some files required for building (lm/build.hpp, loomane_defs.cmake, banner_defs.ini, etc).
    pre:scripts/pio_extra_targets.py # Add the upload_assets target.


[env:banner]
platform = native
board    = native
build_flags = -std=c++20
build_src_filter = -<*> +<lm/version/banner.cpp> +<main_banner.cpp>

[env:native]
platform = native
board    = native
build_flags =
    ${env.build_flags}
    -Iinclude/lm/board/${this.board}  # Explicitly re-add because this is a custom board. When it was added before it would
                                      # evaluate this.board to None, which is bogus.
    -std=c++20
    -DLOOMANE_NATIVE=1
    -DCFG_TUSB_MCU=OPT_MCU_NONE
    -DCFG_TUSB_OS=OPT_OS_NONE
    -DTUP_DCD_ENDPOINT_MAX=10
build_src_filter = ${env.build_src_filter} +<lm/arch/x86_64> +<main.cpp>

[env:lolin_s2_mini]
platform  = espressif32
framework = espidf
board           = lolin_s2_mini
board_build.mcu = esp32s2 # For some reason this doesn't seem to be set correctly.
build_flags =
    ${env.build_flags}
    -DCFG_TUSB_MCU=OPT_MCU_ESP32S2
    -DCFG_TUSB_OS=OPT_OS_FREERTOS

[env:seeed_xiao_esp32s3]
platform  = espressif32
framework = espidf
board           = seeed_xiao_esp32s3
board_build.mcu = esp32s3 # For some reason this doesn't seem to be set correctly.
build_flags =
    ${env.build_flags}
    -DCFG_TUSB_MCU=OPT_MCU_ESP32S3
    -DCFG_TUSB_OS=OPT_OS_FREERTOS
