[env]
custom_loomane_version_major = 0
custom_loomane_version_minor = 3

monitor_speed = 115200
monitor_raw = yes

# Make it so my code editor can find these files too.
build_flags =
    -I$PROJECT_BUILD_DIR/generated/include
    -Iinclude/lm/board/${this.board}
    -DLOOMANE_VERSION_MAJOR=${custom_loomane_version_major}
    -DLOOMANE_VERSION_MINOR=${custom_loomane_version_minor}

extra_scripts =
    pre:scripts/pio_silence.py # Silence some pesky warnings from other projects.
    pre:scripts/pio_gen_version_defs.py # Generate lm/version/defs.hpp.
    pre:scripts/pio_extra_targets.py # Add the upload_assets target.

# Inject the board and mcu into cmake so it can select the right bsp/hal.
board_build.cmake_extra_args =
    -DLOOMANE_BOARD_TYPE=${this.board}
    -DLOOMANE_MCU_TYPE=${this.board_build.mcu}

board_build.partitions = include/lm/board/${this.board}/lm/partitions.csv
; Force PIO to download the FATFS generation tool
board_build.filesystem = fatfs

[env:native]
platform = native
# TODO: Port macros and reenable src/lm/usbd.
build_src_filter = +<*> -<lm/arch/> +<lm/arch/native/> -<lm/usbd/>
build_flags =
    ${env.build_flags}
    -Iinclude/lm/board/native
    -std=c++20
    -DLOOMANE_NATIVE

[env:lolin_s2_mini]
platform = espressif32
framework = espidf
board = lolin_s2_mini
board_build.mcu = esp32s2
monitor_port = COM23
upload_port = COM8

[env:seeed_xiao_esp32s3]
platform = espressif32
framework = espidf
board = seeed_xiao_esp32s3
board_build.mcu = esp32s3
monitor_port = COM23
upload_port = COM8
