[env]
platform = espressif32
framework = espidf
monitor_speed = 115200

# Make it so my code editor can find these files too.
build_flags =
    -I$PROJECT_BUILD_DIR/generated/include
    -Iinclude/lm/board/${this.board}

# Silence some pesky warnings from other projects.
extra_scripts = pre:scripts/pio_pre.py
# Inject the board_id into cmake so it can select the right bsp automatically.
board_build.cmake_extra_args = -DLOOMANE_BOARD_TYPE=${this.board}

[env:lolin_s2_mini]
board = lolin_s2_mini
monitor_port = COM21
upload_port = COM8

[env:seeed_xiao_esp32s3]
board = seeed_xiao_esp32s3
monitor_port = COM21
upload_port = COM8
