services:
  dev:
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - ..:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true

  minimal:
    build:
      context: .
      dockerfile: minimal.dockerfile
    volumes:
      - ..:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true

  ci:
    build:
      context: .
      dockerfile: ci.dockerfile
    volumes:
      - ..:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
