; --- Network ---
[network]
ssid     = loom.a.ne
password = loom.a.ne

; --- Framework ---
[framework]
manager_announce_window_ms = 10

; --- Logging (general) ---
[logging]
toggle    =
color     =
prefix    =
timestamp =
filename  =
; --- Logging (specific) ---
[logging.debug]
toggle =
ansi   =
prefix =
[logging.test]
toggle =
ansi   =
prefix =
[logging.assertion]
toggle =
ansi   =
prefix =
[logging.info]
toggle =
ansi   =
prefix =
[logging.regular]
toggle =
ansi   =
prefix =
[logging.warn]
toggle =
ansi   =
prefix =
[logging.toggle]
toggle =
ansi   =
prefix =
[logging.panic]
toggle =
ansi   =
prefix =

; --- Test ---
[test]
unit =
after_unit =

; --- USB ---
[usb.device]
class =
subclass =
protocol =
vendor =
product =
bcd =
[usb.string]
manufacturer =
product =
serial =
midi =
hid =
uac =
cdc =
msc =

; --- USBIP ---
[usbip]
port =
close_conn_after_devlist =
stall_status_code =
path =
busid =
out_event_queue_size =
[usbip.device]
class =
subclass =
protocol =
vendor =
product =
bcd =
[usbip.string]
manufacturer =
product =
serial =
midi =
hid =
uac =
cdc =
msc =

; --- AUDIO ---
[audio.usb]
microphone_channels =
speaker_channels    =
[audio.usbip]
microphone_channels =
speaker_channels    =
[audio.mesh]
toggle =

; --- CDC ---
[cdc.usb]
toggle     =
strict_eps =
[cdc.usbip]
toggle     =
strict_eps =
[cdc.mesh]
toggle =

; --- HID ---
[hid.usb]
toggle  =
pool_ms =
[hid.usbip]
toggle  =
pool_ms =
[hid.mesh]
toggle =

; --- MIDI ---
[midi.usb]
cable_count =
mode        =
strict_eps  =
[midi.usbip]
cable_count =
mode        =
strict_eps  =

; --- MSC ---
[msc.usb]
toggle     =
strict_eps =
[msc.usbip]
toggle     =
strict_eps =
