name: CI

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build Project
        run: python3 artifact.py -e native

      - name: Run Unit Tests
        run: .artifact/build/native/environment/native/loomane test.unit=on test.after_unit=halt
